access_token = "9fcfc6e2-6ae6-4ec3-9e5c-abb493a3fd25"
device_id = "4b43efe0-eb1e-4865-ae3b-e33cf172f25c"
license_key = "2vl4R67F-4u80b6TA-67Si3CL4"
private_key = "gCWs/mzkxk9KaDNwynWYYF2JigH0iaZ+9joDWHqdJ2I="
